#!/bin/sh

# Requires ffmpeg (audio splitting) and my `tag` wrapper script.

#[ ! -f "$2" ] && printf "The first file should be the audio, the second should be the timecodes.\\n" && exit

inputaudio="$1"
timecodes="$2"
booktitle="$3"
author="$4"
year="$5"

# Get a safe file name from the book.
escbook="$(echo "$booktitle" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"

! mkdir -p "$escbook" &&
    echo "Do you have write access in this directory?" &&
    exit 1

# As long as the extension is in the tag script, it'll work.
# ext="opus"
ext="${1#*.}"

# Get the total number of tracks from the number of lines.
total="$(wc -l < "$2")"

while read -r x;
do
    end="$(echo "$x" | cut -d' ' -f1)"
    file="$escbook/$(printf "%.2d" "$track")-$esctitle.$ext"
    if [ -n "$start" ]; then
        echo "From $start to $end; $track $title"
        ffmpeg -i "$inputaudio" -nostdin -y \
			-loglevel -8 \
			-metadata artist="$author" -metadata title="$title" \
			-metadata album="$booktitle" -metadata year="$year" \
			-metadata track="$track" \
			-ss "$start" -to "$end" \
			-vn -c copy "$file"
    fi
    title="$(echo "$x" | cut -d' ' -f 2-)"
    esctitle="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
    track="$((track+1))"
    start="$end"
done < "$timecodes"
# The last track must be done outside the loop.

file="$escbook/$(printf "%.2d" "$track")-$esctitle.$ext"
echo "From $start to the end; $track $title"
ffmpeg -i "$inputaudio" -nostdin -y \
	-loglevel -8 \
	-metadata artist="$author" -metadata title="$title" \
	-metadata album="$booktitle" -metadata year="$year" \
	-metadata track="$track" \
	-ss "$start" \
	-vn -c copy "$file"